crm/urls.py
from django.conf.urls import url

from crm import views
app_name = 'crm'

urlpatterns = [
    url(r'^$', views.ContractListView.as_view(), name="contracts_list"),

    url(r'^contract_add/$', views.ContractCreateView.as_view(), name='contract_add'),
    url(r'^contract/(?P<contract_id>\w+)/$', views.contract_view, name='contract_view'),
    url(r'^contract/(?P<contract_id>\w+)/contract_edit/$', views.contract_edit, name='contract_edit'),
    url(r'^contract/(?P<contract_id>\w+)/history/$', views.contract_history, name='contract_history'),
    ]

project/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse_lazy

from commons.models import BaseStampedModel
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from django.db import transaction
import reversion
from mptt.models import MPTTModel, TreeForeignKey

from ich_bau.profiles.notification_helper import Send_Notification
from ich_bau.profiles.models import Profile, PROFILE_TYPE_USER, PROFILE_TYPE_FOR_TASK
from ich_bau.profiles.messages import *

from project.repo_wrapper import *

def Get_ContentType( arg_model ):
    return ContentType.objects.get( app_label = 'project', model = arg_model )

# access level
PROJECT_ACCESS_NONE  = 0 # нет доступа
PROJECT_ACCESS_VIEW  = 1 # просмотр
PROJECT_ACCESS_WORK  = 2 # может что-то делать: создавать и редактировать задачи, комментировать, закрывать и открывать задачи
PROJECT_ACCESS_ADMIN = 3 # админить проект - создавать и редактировать вехи, добавлять-удалять участников
# правила следующие
# для открытых проектов:
# - любой аноним может смотреть
# - любой авторизованный юзер может смотреть и работать.
# - Админить может только их админ. Тогда в чем смысл участника? Что на него можно назначать задачи!
# для закрытых проектов:
# - аноним и авторизованный не участник их не видит
# - авторизованный участник может работать
# - админ может админить


# виды приватности проекта
PROJECT_VISIBLE_PRIVATE = 0
PROJECT_VISIBLE_VISIBLE = 1
PROJECT_VISIBLE_OPEN    = 2

PROJECT_VISIBLE_LIST = ( PROJECT_VISIBLE_PRIVATE, PROJECT_VISIBLE_VISIBLE, PROJECT_VISIBLE_OPEN )

PROJECT_VISIBLE_LIST_CHOICES = (
    ( PROJECT_VISIBLE_PRIVATE, 'Private' ),
    ( PROJECT_VISIBLE_VISIBLE, 'Visible' ),
    ( PROJECT_VISIBLE_OPEN, 'Open' ),
    )

@reversion.register()
class Project(BaseStampedModel):
    # shortname = models.CharField(max_length=255)
    fullname = models.CharField(max_length=255, verbose_name = 'Full name!')
    active_flag=models.BooleanField(blank=True, default=True)
    # доступность проекта для пользователей
    private_type=models.PositiveSmallIntegerField( blank=False, null=False, default = PROJECT_VISIBLE_PRIVATE, verbose_name = 'Private project' )
    use_sub_projects=models.BooleanField(blank=False, default=False)
    description = models.TextField(blank=True, null=True)
    repo_name = models.CharField( max_length=255, blank=True, null = True )

    class Meta:
        ordering = ['fullname']

    def save(self, *args, **kwargs):
        if self.private_type in PROJECT_VISIBLE_LIST: # check for private visible type
            return super(Project, self).save(*args, **kwargs)
        else:
            raise Exception("Cannot save - wrong project private flag!")

    # полный список членов проекта, независимо от статуса подтверждения. Возвращает объекты Member
    def GetMemberList( self ):
        return Member.objects.filter( project = self )

    # список полных (полностью подтвержденных) членов проекта. Возвращает объекты Member
    def GetFullMemberList( self ):
        q = Member.objects.filter( project = self, team_accept__isnull = False, member_accept__isnull = False )
        return q

    # список полных (полностью подтвержденных) админов проекта. Возвращает объекты Member
    def GetFullMemberAdminList( self ):
        q = self.GetFullMemberList().filter( admin_flag = True )
        return q

    # список профилей полных (полностью подтвержденных) членов проекта. Возвращает объекты Profile
    def GetFullMemberProfiles( self ):
        q = Profile.objects.filter( member_profile__project = self, member_profile__team_accept__isnull = False, member_profile__member_accept__isnull = False )
        return q

    # список юзеров полных (полностью подтвержденных) членов проекта. Возвращает объекты User
    def GetFullMemberUsers( self ):
        q = User.objects.filter( profile__in=self.GetFullMemberProfiles() )
        return q

    def is_member( self, arg_user ):
        if ( arg_user is None ) or ( not arg_user.is_authenticated ):
            return False # аноним никогда не участник
        else:
            return self.GetFullMemberProfiles().filter( user = arg_user ).exists()

    def is_admin( self, arg_user ):
        if ( arg_user is None ) or ( not arg_user.is_authenticated ):
            return False # аноним никогда не админ
        else:
            return self.GetFullMemberAdminList().filter( member_profile__user = arg_user ).exists()

    def can_admin( self, arg_user ):
        # админить могут только админы, и для открытых, и для закрытых проектов
        # создавать и редактировать вехи
        return self.is_admin( arg_user )

    def is_project_visible(self):
        return self.private_type in ( PROJECT_VISIBLE_VISIBLE, PROJECT_VISIBLE_OPEN )

    def can_view( self, arg_user ):
        # если проект открытый, то смотреть могут все
        # если закрытый, то только члены
        if self.is_project_visible():
            return self.is_member( arg_user )
        else:
            return True

    # может ли юзер подать заявку на включение
    def can_join( self, arg_user ):
        return ( self.is_project_visible() ) and ( arg_user.is_authenticated ) and ( not self.GetMemberList().filter( member_profile__user = arg_user ).exists() )

    def user_access_level( self, arg_user ):
        member_level = None
        # если пользователь не авторизован, то доступ только к открытым проектам и только на просмотр
        if ( arg_user is None ) or ( not arg_user.is_authenticated ):
            if self.is_project_visible():
                return PROJECT_ACCESS_VIEW
            else:
                return PROJECT_ACCESS_NONE
        else:
            # предполагается 1 или ни единого.
            try:
                m = self.GetMemberList().get( member_profile__user = arg_user )
                if ( not m ) or ( m is None ):
                    member_level = None
                else:
                    if not ( m.team_accept is None ) and not( m.member_accept is None ):
                        if m.admin_flag:
                            return PROJECT_ACCESS_ADMIN
                        else:
                            return PROJECT_ACCESS_WORK
                    else:
                        return PROJECT_ACCESS_VIEW
            except:
                member_level = None

        if member_level is None:
            if self.is_project_visible():
                return PROJECT_ACCESS_VIEW
            else:
                return PROJECT_ACCESS_NONE

    # список задач проекта.
    #   arg_opened = None значит все
    #   arg_opened = True значит открытые
    #   arg_opened = False значит закрытые
    def Get_Tasks( self, arg_opened = None ):
        q = Task.objects.filter( project = self )
        if arg_opened is None:
            return q
        else:
            return q.filter(finished_fact_at__isnull = arg_opened )

    def __str__(self):
        return self.fullname

    def get_absolute_url(self):
        return "/project/project/%i/" % self.id

    def description_html(self):
        return self.description

    def have_repo( self ): # True - да, repo есть
        s = self.repo_name
        return ( not ( s is None ) ) and ( s != '' )

    def add_repo_access( self ):
        # дать доступ к repo
        if self.have_repo():
            # дать доступ по всему списку членов проекта
            user_dict = { settings.REPO_SVN.get('SVN_ADMIN_USER') : settings.REPO_SVN.get('SVN_ADMIN_PASSWORD') }

            member_profiles = self.GetFullMemberProfiles()

            for mp in member_profiles:
                user_dict[ mp.user.username ] = mp.repo_pw

            Add_User_to_Repo( self.repo_name, user_dict )

class Member(BaseStampedModel):
    project = models.ForeignKey(Project, on_delete=models.PROTECT, blank=False, null=False )
    member_profile = models.ForeignKey( Profile, on_delete=models.PROTECT, blank=False, null=False, related_name = "member_profile" )
    admin_flag=models.BooleanField(blank=True, default=False, verbose_name = 'Admin')
    # флаг подтверждения со стороны админа проекта
    team_accept = models.DateTimeField( blank=True, null=True )
    # флаг подтверждения со стороны участника
    member_accept = models.DateTimeField( blank=True, null=True )

    class Meta:
        unique_together = ("project", "member_profile")

    def save(self, *args, **kwargs):
        super(Member, self).save(*args, **kwargs)
        # послать уведомление. самому себе посылать не надо.
        if ( self.member_profile.user != self.modified_user ) and ( self.member_accept is None ):
            message_str = project_msg2json_str( MSG_NOTIFY_TYPE_ASK_ACCEPT_ID, arg_project_name = self.project.fullname )
            project_type = Get_ContentType( arg_model='project' )
            Send_Notification( self.modified_user, self.member_profile.user, project_type, self.project.id, MSG_NOTIFY_TYPE_ASK_ACCEPT_ID, message_str, reverse_lazy('project:project_view_members', kwargs={ 'project_id': self.project.id} ) )

    def set_user_want_join( self, arg_user ):
        self.member_profile = arg_user.profile
        self.member_accept = timezone.now()
        self.set_change_user(arg_user)
        self.save()
        message_str = project_msg2json_str( MSG_NOTIFY_TYPE_USER_WANT_JOIN_ID, arg_project_name = self.project.fullname )
        project_type = Get_ContentType( arg_model='project')

        for a in self.project.GetFullMemberAdminList():
            Send_Notification( arg_user, a.member_profile.user, project_type, self.project.id, MSG_NOTIFY_TYPE_USER_WANT_JOIN_ID, message_str, self.project.get_absolute_url() )


project/forms.py
# project forms

from django import forms
from project.models import Project, PROJECT_VISIBLE_LIST_CHOICES, PROJECT_VISIBLE_PRIVATE, Task, TaskComment, Milestone, Member, TaskDomain, TaskLink, TaskProfile, TaskCheckList, Task2Domain, Get_Profiles_Available2Task
from ich_bau.profiles.models import PROFILE_TYPE_USER

from django.forms.widgets import HiddenInput, CheckboxSelectMultiple
from mptt.forms import TreeNodeChoiceField

from commons.editors import DateTime_Field, TextEditor_Field

class ProjectForm(forms.ModelForm):
    description = TextEditor_Field(arg_required=False)
    # https://docs.djangoproject.com/en/2.2/ref/forms/api/#dynamic-initial-values
    # https://docs.djangoproject.com/en/2.2/ref/forms/widgets/#widgets-inheriting-from-the-select-widget
    private_type = forms.ChoiceField( label='Project visible level',
                                      widget=forms.RadioSelect,
                                      choices=PROJECT_VISIBLE_LIST_CHOICES,
                                      initial = PROJECT_VISIBLE_PRIVATE )

    class Meta:
        model = Project
        fields = ['fullname', 'private_type', 'active_flag', 'use_sub_projects', 'description' ]

class MilestoneForm(forms.ModelForm):
    planned_at = DateTime_Field( False )
    finished_at = DateTime_Field( False )

    class Meta:
        model = Milestone
        fields = ['fullname', 'planned_at', 'finished_at' ]

from ich_bau.profiles.models import Profile, Get_Users_Profiles

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['member_profile', 'admin_flag' ]

    def __init__(self, *args, **kwargs):
        super(MemberForm, self).__init__(*args, **kwargs)
        # форма работает в режиме создания (смотрим 'initial')
        p = kwargs.pop('initial', None)['project']

        # отображать только свободных людей
        if not ( p is None):
            self.fields['member_profile'].queryset = Get_Users_Profiles().exclude( member_profile__project_id = p.id )

class TaskForm(forms.ModelForm):
    description = TextEditor_Field(arg_required=False)

    class Meta:
        model = Task
        fields = ['fullname', 'description', 'milestone', 'holder', 'important', 'kind', ]

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        # форма работает в 2х режимах - создания (смотрим 'initial') и редактирования (смотрим 'instance') свойства.
        instance = kwargs.pop('instance', None)
        if (instance is None):
            pop = kwargs.pop('initial', None)
            p = pop['project']
        else:
            p = instance.project

        # отображать вехи и пользователей только этого проекта
        if not ( p is None):
            self.fields['milestone'].queryset = Milestone.objects.filter( project = p, finished_at__isnull = True )
            list = p.GetFullMemberProfiles()
            self.fields['holder'].queryset = list

class TaskLinkedForm(forms.ModelForm):
    subtasks=forms.ModelMultipleChoiceField( Task.objects, help_text="subtask", required=True, widget=CheckboxSelectMultiple() )

    def __init__(self, *args, **kwargs):
        arg_qs = kwargs.pop('arg_qs', None)
        super(TaskLinkedForm, self).__init__(*args, **kwargs)

        if ( arg_qs != "" ):
            self.fields['subtasks'].queryset = arg_qs

    class Meta:
        model = TaskLink
        fields = ['subtasks']

class TaskProfileForm(forms.ModelForm):
    profile=forms.ModelChoiceField( Profile.objects, help_text="profile", required=True )
    priority=forms.BooleanField( label = 'Responsible', help_text="Responsible or interested", required=False )

    def __init__(self, *args, **kwargs):
        argmaintaskid = kwargs.pop('argmaintaskid', None)
        add_user = kwargs.pop('add_user', None)
        super(TaskProfileForm, self).__init__(*args, **kwargs)

        if (argmaintaskid != "" ):
            main_task = Task.objects.get( id = argmaintaskid )
            q = Get_Profiles_Available2Task( argmaintaskid ) # base query - all types profiles, unassigned
            if add_user:
                self.fields['profile'].queryset = q.filter( profile_type = PROFILE_TYPE_USER ) # only users
            else:
                self.fields['profile'].queryset = q.exclude( profile_type = PROFILE_TYPE_USER ) # all except users

    class Meta:
        model = TaskProfile
        fields = ['profile', 'priority' ]

class TaskDomainForm(forms.ModelForm):
    taskdomain = TreeNodeChoiceField(queryset=TaskDomain.objects.all())

    def __init__(self, *args, **kwargs):
        argmaintaskid = kwargs.pop('argmaintaskid', None)
        super(TaskDomainForm, self).__init__(*args, **kwargs)

        if (argmaintaskid != "" ):
            #main_task = Task.objects.get( id = argmaintaskid )
            self.fields['taskdomain'].queryset = TaskDomain.objects.all().exclude( domain2task__task = argmaintaskid )

    class Meta:
        model = Task2Domain
        fields = ['taskdomain']

class TaskCommentForm(forms.ModelForm):
    comment = TextEditor_Field()

    class Meta:
        model = TaskComment
        fields = ['comment' ]

class TaskCheckListForm(forms.ModelForm):
    class Meta:
        model = TaskCheckList
        fields = ['checkname', 'check_flag' ]

project/templates/project/index.html
{% extends "site_base.html" %}

{% block head_title %}Project{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">

<h1>Projects 
{% if can_add_project %}
<a class="btn btn-default" href="/project/project_add/"><i class="fa fa-plus"></i>Create project</a>
{%endif%}
</h1>

<ul class="nav nav-tabs">
  <li role="presentation" {% if filter_type == '' %} class="active" {% endif %}><a href="/project/">Mine</a></li>
  <li role="presentation" {% if filter_type == 'all_available' %} class="active" {% endif %}><a href="/project/all_available">Available</a></li>
  <li role="presentation" {% if filter_type == 'search_public' %} class="active" {% endif %}><a href="/project/search_public/">Search public</a></li>
  <li role="presentation" {% if filter_type == 'all_public' %} class="active" {% endif %}><a href="/project/all_public/">All public</a></li>
  <li role="presentation" {% if filter_type == 'task_search' %} class="active" {% endif %}><a href="/project/task_search/">Task search</a></li>
</ul>

<p></p>

{% if filter_type == 'search_public' %}
{% load bootstrap %}
    <div class="row">
        <div class="col-md-5">

    <form action="" method="get">
        {{ filter.form|bootstrap }}
        <input type="submit" class="btn btn-info" />
    </form>
    </div>
    </div>
    <br>
    {% for obj in filter.qs %}
        <a href="{{ obj.get_absolute_url }}">{{ obj.fullname }}</a><br />
    {% endfor %}
    <p>{{filter.qs.count}} found.</p>

{% else %}

{% if filter_type == '' and not request.user.is_authenticated %}

Please, log in to see your projects.

{% else %}

{% if filter_type == 'task_search' %}
    <div class="row">
        <div class="col-md-5">

    <form action="" method="get">
        {{ filter.form|bootstrap }}
        <input type="submit" class="btn btn-info" />
    </form>
    </div>
    </div>
    <h2>Search for tasks</h2>
    {% include "project/task_list.html" with table_mode='index' %}
{% else %}
    {% include "project/project_list.html" %}
{% endif %}


{% endif %}

{% endif %}

{% if filter_type == '' %}

<h3>Tasks assigned to you</h3>

{% if not request.user.is_authenticated %}
Please, log in to see your tasks.
{% else %}
{% include "project/task_list.html" with table_mode='index' %}
{% endif %}
{% endif %}

        </div>
    </div>

{% endblock %}

project/templates/project/milestone.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{{milestone}}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
        
<ol class="breadcrumb">
<li>  <a href="{% url 'project:index' %}">Projects</a></li></li>
<li>  <a href="{{ milestone.project.get_absolute_url }}">{{ milestone.project }}</a></li>
</ol>
        
<h1>{{milestone}}</h1>

<p>{% if milestone.planned_at %}Plan date: {{milestone.planned_at|date}} {% endif %}</p>
<p>{% if milestone.finished_at %}Fact finish date: {{milestone.finished_at|date}} {% endif %}</p>

{% if user_can_admin %}
<a class="btn btn-default" href="{{milestone.get_absolute_url}}edit"><i class="fa fa-pencil-square-o"></i> Edit milestone</a>

{% if milestone.created_at == milestone.modified_at %}
no history to view

{% else %}
<a href="{{milestone.get_absolute_url}}history">History</a>
{% endif %}

{% endif %}

<h2>Tasks {% if not milestone.finished_at %}{% if user_can_admin or user_can_work %}<a class="btn btn-default" href="/project/task_add_to_milestone/{{milestone.id}}/"><i class="fa fa-plus"></i> {% trans "Create task" %}</a>{% endif %}{% endif %}</h2>

{% include "project/task_list.html" with table_mode='milestone' %}

</div>
</div>

<small>This page was last modified on {{ milestone.modified_at }}</small>
    
{% endblock %}

project/templates/project/milestone_form.html
{% extends 'site_base.html' %}

{% load bootstrap %}

{% block body_class %}milestone{% endblock %}

{% block head_title %}
{% if milestone.pk %}
Edit milestone
{% else %}
Create milestone
{% endif %}

{% endblock %}


{% block body %}
<div class="row">
<div class="col-md-9">

{{ form.media }}

        <form class="span6" id="milestone_form" method="post" action="" enctype="multipart/form-data">

                {% if milestone.pk %}
                    <legend>Edit milestone</legend>
                {% else %}
                    <legend>Create milestone</legend>
                {% endif %}

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}

                {{ field|bootstrap }}
            {% endfor %}


            <button class="btn btn-primary" type="submit" name="submit">Save</button>
        </form>
</div>
</div>
{% endblock %}

{% block scripts %}
{{block.super}}
<script type="text/javascript" src="/site_media/static/bootstrap3_datetime/js/moment.min.js"></script>
<script type="text/javascript" src="/site_media/static/bootstrap3_datetime/js/bootstrap-datetimepicker.min.js"></script>
{%endblock%}

{% block styles %}
{{block.super}}
<link href='/site_media/static/bootstrap3_datetime/css/bootstrap-datetimepicker.min.css' rel='stylesheet' />
{%endblock%}

project/templates/project/milestone_history.html
{% extends 'site_base.html' %}

{% load bootstrap %}

{% block head_title %}{{milestone}} history{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
        
<h1>{{milestone}} history</h1>
<a href="{{milestone.get_absolute_url}}">back</a>

    <table class="table table-striped">
    <thead>
    <tr>
    <th>Date-time</th>
    <th>Full name</th>
    <th>Planned at</th>
    <th>Finished at</th>
    <th>User</th>
    </tr>
    </thead>
    <tbody>
        {% for v in versions %}
        <tr>
        <td>{{v.revision.date_created}}</td>
        <td>{{v.field_dict.fullname}}</td>
        <td>{{v.field_dict.planned_at|date}}</td>
        <td>{{v.field_dict.finished_at|date}}</td>
        <td><a href="{% url 'profiles_detail' pk=v.revision.user.profile.pk %}">{{v.revision.user}}</a></td>
        </tr>
        {% endfor %}

    </tbody>
    <table>  

</div>
</div>

<small>This page was last modified on {{ milestone.modified_at }}</small>
    
{% endblock %}

project/templates/project/project.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load bootstrap %}
{% load thumbnail %}
{% load template_arithmetic_tag %}

{% block head_title %}{{project}}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
<h1>{{project}}
{% if not project.is_project_visible %}
<i class="fa fa-lock"></i>
{% endif %}

{% if not project.active_flag %}
   <span class="label label-primary">Closed</span>
{% endif %}

</h1>

<ul class="nav nav-tabs">
  <li role="presentation" {% if show_page == 'title' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}">{% trans "Project" %}</a></li>
  <li role="presentation" {% if show_page == 'members' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}members/">{% trans "Members" %}</a></li>
  <li role="presentation" {% if show_page == 'last_actions' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}last_actions/">{% trans "Last activities" %}</a></li>

  {% if show_file_page %}
    <li role="presentation" {% if show_page == 'files' %} class="active" {% endif %}><a href="{% url 'project:project_view_files' project_id=project.pk %}">{% trans "Files" %}</a></li>
  {% endif %}
  <li role="presentation" {% if show_page == 'milestones' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}milestones/">{% trans "Milestones" %}</a></li>
</ul>

{% if show_page == 'title' %}

<p>Project description</p>

{% if project.description %}
{{ project.description_html|safe }}
{% endif %}

{% if user_can_admin %}
<a class="btn btn-default" href="{{project.get_absolute_url}}project_edit"><i class="fa fa-pencil-square-o"></i> {% trans "Edit project" %}</a>
{% endif %}

{% if project.created_at == project.modified_at %}
no history to view

{% else %}
<a href="{{project.get_absolute_url}}history">History</a>
{% endif %}

<h2>{% trans "Tasks" %} {% if user_can_admin or user_can_work %}<a class="btn btn-default" href="/project/task_add/{{project.id}}/"><i class="fa fa-plus"></i> {% trans "Create task" %}</a>{% endif %}</h2>

<ul class="nav nav-tabs">
  <li role="presentation" {% if filter_type == '' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}">{% trans "Open" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_closed' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}closed_task/">{% trans "Closed" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_assigned' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}assigned_task/">{% trans "Assigned" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_unassigned' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}unassigned_task/">{% trans "Unassigned" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_by_domain' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}task_by_domain/">{% trans "Domain" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_search' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}search_task/">{% trans "Search" %}</a></li>
</ul>

{% if filter_type == 'filter_task_search' %}
    <div class="row">
        <div class="col-md-5">

    <form action="" method="get">
        {{ filter.form|bootstrap }}
        <input type="submit" class="btn btn-info" />
    </form>
    </div>
    </div>
{% else %}
    {% if filter_type == 'filter_task_by_domain' %}
        {% load mptt_tags %}

        <div class="row">

            <ul class="list-group">
                {% recursetree domains %}
                    <li class="list-group-item" >
                    {% if node.pk == selected_domain %}<strong>{% endif %}
                    <a href="{% url 'project:project_view_task_for_domain' project.pk node.pk %}">{{node.name}}</a>


                    {% if node.pk == selected_domain %}</strong>{% endif %}

                        {% if not node.is_leaf_node %}
                            <ul class="list-group">
                            {{ children }}
                            </ul>
                        {% endif %}
                    </li>
                {% endrecursetree %}
            </ul>

        </div>
    {% endif %}

{% endif %}

{% include "project/task_list.html" with table_mode='project' %}

{% comment %} end if TITLE {% endcomment %}
{% endif %}

{% if show_page == 'members' %}

<h2>{% trans "Members" %} {% if user_can_admin %}<a class="btn btn-default" href="/project/member_add/{{project.id}}/"><i class="fa fa-plus"></i> {% trans "Add member" %}</a>{% endif %}</h2>

{% include "project/project_members_list.html" %}
{% endif %}

{% if show_page == 'last_actions' %}

<h2>{% trans "Recent project activity" %}</h2>

<table class="table table-striped">
<thead>
<tr>
    <th>Date time</th>
    <th>User</th>
    <th>Comment</th>
    <th>Task</th>
</tr>
</thead>

<tbody>
    {% for c in last_actions %}
        <tr>
            <td>{{c.modified_at}}</td>
            <td>{{c.modified_user}}</td>
            <td>{{c.comment|safe|truncatewords_html:12}}</td>
            <td><a href="{{c.parenttask.get_absolute_url}}">{{c.parenttask}}</a></td>
        </tr>
    {%endfor%}
</tbody>
</table>

{% endif %}


{% if show_page == 'files' %}
<h2>Files</h2>

{% include "project/project_repo.html" %}


{% comment %} end if FILES {% endcomment %}
{% endif %}

{% if show_page == 'milestones' %}
<h2>{% trans "Milestones" %}{% if user_can_admin %} <a class="btn btn-default" href="/project/milestone_add/{{project.id}}/"><i class="fa fa-plus"></i> {% trans "Create milestone" %}</a>{% endif %}</h2>

{% include "project/project_milestones.html" %}

{% comment %} end if MILESTONES {% endcomment %}
{% endif %}

</div>
</div>

{% endblock %}